### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by nnocase** [shadowcz007/AR-lab#1]
(node:2849) UnhandledPromiseRejectionWarning: FetchError: request to http://0.0.0.0:8891/segment failed, reason: connect ECONNREFUSED 0.0.0.0:8891
    at ClientRequest.<anonymous> (/Users/xgf/code/AR-lab/client/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:2849) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by shadowcz007** [comment]
service里的python服务需要开启

**Comment by shadowcz007** [comment]
> (node:2849) UnhandledPromiseRejectionWarning: FetchError: request to http://0.0.0.0:8891/segment failed, reason: connect ECONNREFUSED 0.0.0.0:8891
> at ClientRequest. (/Users/xgf/code/AR-lab/client/node_modules/node-fetch/lib/index.js:1461:11)
> at ClientRequest.emit (events.js:315:20)
> at Socket.socketErrorListener (_http_client.js:469:9)
> at Socket.emit (events.js:315:20)
> at emitErrorNT (internal/streams/destroy.js:106:8)
> at emitErrorCloseNT (internal/streams/destroy.js:74:3)
> at processTicksAndRejections (internal/process/task_queues.js:80:21)
> (node:2849) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

service里的python服务需要开启

**Comment by nnocase** [comment]
OK，thanks
