### ISSUE TITLE
client报错

### ISSUE THREAD

**Issue by Xktao** [shadowcz007/AR-lab#4]
npm ERR! code 1
npm ERR! path D:\AR-lab-main\client\node_modules\lzma-native
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.14.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.7.0 found at "C:\Users\xktao\Anaconda3\python.exe"
npm ERR! gyp info find VS using VS2019 (16.7.30621.155) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! (node:9188) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will
 be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn C:\Users\xktao\Anaconda3\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'D:\\AR-lab-main\\client\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\AR-lab-main\\client\\node_modules\\lzma-native\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\AR-lab-main\\client\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\xktao\\AppData\\Local\\node-gyp\\Cache\\16.14.2\\include\\node\\common.gypi',

npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xktao\\AppData\\Local\\node-gyp\\Cache\\16.14.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=D:\\AR-lab-main\\client\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\xktao\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.14.2
\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\AR-lab-main\\client\\node_modules\\lzma-native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\AR-lab-main\\client\\node_modules\\lzma-native\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_path in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (D:\AR-lab-main\client\node_modules\node-gyp\lib\configure.js:351:1
6)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "E:\\Program Files (x86)\\node.exe" "D:\\AR-lab-main\\client\\node_modules\\node-gyp\\bin\\nod
e-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\AR-lab-main\client\node_modules\lzma-native
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xktao\AppData\Local\npm-cache\_logs\2022-04-21T06_53_59_491Z-debug-0.log

**Comment by shoukailiang** [comment]
我也是

**Comment by shoukailiang** [comment]
PS C:\Users\shouk\Downloads\AR-lab-main\AR-lab-main\client> npm i 
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\shouk\\Downloads\\AR-lab-main\\AR-lab-main\\client\\node_modules\\robotjs',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\shouk\Downloads\AR-lab-main\AR-lab-main\client\node_modules\robotjs'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\shouk\\Downloads\\AR-lab-main\\AR-lab-main\\client\\node_modules\\robotjs'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\shouk\Downloads\AR-lab-main\AR-lab-main\client\node_modules\lzma-native
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.14.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.7.9 found at "C:\Users\shouk\AppData\Local\Programs\Python\Python37\python.exe"    
npm ERR! gyp info find VS using VS2019 (16.11.32228.343) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! (node:49924) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only. 
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn C:\Users\shouk\AppData\Local\Programs\Python\Python37\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\shouk\\Downloads\\AR-lab-main\\AR-lab-main\\client\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\shouk\\Downloads\\AR-lab-main\\AR-lab-main\\client\\node_modules\\lzma-native\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\shouk\\Downloads\\AR-lab-main\\AR-lab-main\\client\\node_modules\\node-gyp\\addon.gypi',     
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\shouk\\AppData\\Local\\node-gyp\\Cache\\16.14.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\shouk\\AppData\\Local\\node-gyp\\Cache\\16.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\shouk\\Downloads\\AR-lab-main\\AR-lab-main\\client\\node_modules\\node-gyp',  
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\shouk\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.14.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\shouk\\Downloads\\AR-lab-main\\AR-lab-main\\client\\node_modules\\lzma-native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\shouk\\Downloads\\AR-lab-main\\AR-lab-main\\client\\node_modules\\lzma-native\\build',       
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_path in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\shouk\Downloads\AR-lab-main\AR-lab-main\client\node_modules\node-gyp\lib\configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shouk\\Downloads\\AR-lab-main\\AR-lab-main\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\shouk\Downloads\AR-lab-main\AR-lab-main\client\node_modules\lzma-native
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shouk\AppData\Local\npm-cache\_logs\2022-04-26T05_12_36_248Z-debug-0.log

**Comment by YU-Anthony** [comment]
请问这个问题现在解决了吗？
